-- create deptid,deptname,deptloc
CREATE TABLE DEPARTMENT (
  deptId INTEGER PRIMARY KEY,
   deptname TEXT NOT NULL,

 


  deptloc TEXT NOT NULL
);

 

-- insert
INSERT INTO DEPARTMENT VALUES(1,'PRANAV','PUNE');
INSERT INTO DEPARTMENT VALUES(2,'KUNAL','MUMBAI');
INSERT INTO DEPARTMENT VALUES(4,'PRATIK','PUNE');
INSERT INTO DEPARTMENT VALUES(5,'PREM','PUNE');
INSERT INTO DEPARTMENT VALUES(3,'RAM','HYDRABAD');

 

-- fetch 
SELECT * FROM DEPARTMENT 